server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/javacare?currentSchema=users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: users

  flyway:
    enabled: true
    locations: classpath:db/migration
    defaultSchema: users

graphql:
  path: /graphql
  schema:
    locations: classpath:graphql/
