services:

  postgres:
    image: postgres:16
    container_name: javacare-postgres
    environment:
      POSTGRES_DB: javacare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - javacare-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: javacare-rabbitmq
    ports:
      - "5672:5672"   # Porta para comunicação da aplicação
      - "15672:15672" # Porta do painel de administração web
    networks:
      - javacare-network

volumes:
  postgres_data:

networks:
  javacare-network:
    driver: bridge
