FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /build
COPY . .
RUN mvn -pl history -am clean package spring-boot:repackage -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /build/history/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]