server:
  port: 8080

spring:
  application:
    name: scheduling-service

  datasource:
    url: jdbc:postgresql://postgres:5432/javacare
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
