server:
  port: 8080

spring:
  application:
    name: scheduling-service

  datasource:
    url: jdbc:postgresql://postgres:5432/javacare?currentSchema=schedulings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: schedulings

  flyway:
    enabled: true
    locations: classpath:db/migration
    defaultSchema: schedulings

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

services:
  user:
    url: http://user:8083
